# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6045cc6186f6e955579c0bce1190eda4f6701c7a80fa248d2bb7e2e3ec78c18ec801010ea34ea6718184c592c0c2b843b4b50464dff15d370474b3ec597a2ad

test:
  secret_key_base: 3b4506c61c94638a5f658fe23a58a630044525aade90811ca6dc8ed5667ee2915dd98846a1b4da7d7611d8eab883c30649dc2121be911f0e8c0b44d45ce4bd3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
